#!/bin/bash
# Start script for freedv rade version
# Specify a config file to use (optional) default is ~/.freedv
# e.g. freedv-start -f myfreedv.conf
###################################
#set -x
# Run sound setup
. freedv-sound-setup || exit 1
. pw-restore-vols
###################################
# Add path to rigctld if built locally
    EXT_DIST_BIN="/home/baz/freedv-rade/freedv-gui/build_linux/external/dist/bin/"
    if ! command -v rigctld &>/dev/null; then
        export PATH="$EXT_DIST_BIN:$PATH"
    fi
####################################
# Edit and uncomment (remove #) the 'rigcltd...' line below with your radio code (-m) and USB port (-r) to start rigctld at freedv launch.
# Mine below is for the TS-450S, yours will be different probably without the --set-conf..... part - but leave the '&' at the end of that line.
# You can look up your rig code number using 'rigctl -l' in a terminal.
# Uncomment the next line to use Hamlib NET rigctl.
#
rigctld -m 2003 -r /dev/ttyUSB0 -T 0.0.0.0 -t 4532 --set-conf=serial_handshake=None &
#
#
# You will then in freedv set the radio model to 'Hamlib NET rigctl' in the 'CAT and PTT config' and the 'Serial Device' to 'localhost:4532'
# Other computers wishing to communicate with the radio will be able to use <IP of this machine>:4532. You will need port 4532/tcp open in
# this  machine's firewall if active.
####################################

# Function to kill all rigctld processes
killrigctld() {
parr=$(ps aux|grep [r]igctld|tr -s ' '|cut -d ' ' -f2)
for p in ${parr[@]};do
    kill -9 $p
done
}

cd /home/baz/freedv-rade/freedv-gui

# Activate virtual environment
. ./rade-venv/bin/activate

cd build_linux

# Ensure model19_check3 symlink exists
if ! [[ -h model19_check3 ]]; then
    ln -s $(pwd)/rade_src/model19_check3 model19_check3
fi

# Set Python path for dynamic module access
export PYTHONPATH="$(pwd)/rade_src:$PYTHONPATH"

# Force GTK to use X11 for window positioning under Wayland
export GDK_BACKEND=x11

# Run the FreeDV RADE GUI
src/freedv
##2<&1| grep -i "ptt\|cts\|serial"

# Deactivate venv on exit
deactivate

# Uncomment the next line to totally kill rigctld on closing freedv.
killrigctld

# Kill BPF and remove LOCKFILE
cd

. pw-save-vols
sleep 1
. freedv-sound-stop

echo "FreeDV stopped"
