#!/bin/bash

if (( ${#1} > 0 )); then
    input_file=$1
else
    input_file=saved_links.txt
fi

while IFS= read -r line; do
    echo "Linking: $line"  # Debug output
    pw-link $line
done < $input_file


