#!/bin/bash

if (( ${#1} > 0 )); then
    output_file=$1
else
    output_file=saved_links.txt
fi

pw-link -l |
awk '
    $0 !~ /\|/ { prev = $0; next }

    /->/ {
        sub(/\|/, "", $0)            # remove pipe
        gsub(/[ ]+->[ ]+/, " ", $0)  # remove arrow, leave one space
        print prev $0                # concatenate, don’t add OFS
    }
' > $output_file  # Remove unwanted "> " from the destination

echo "Links saved to $output_file"



